<style>
	.success{
		background-color: lightgreen;
	}
	.failure{
		background-color: red;
	}
	.notice{
		background-color: orange;
	}

</style>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
 
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<div class="header">
	<nav class="navbar bg-info" data-bs-theme="dark">
				<a class=" btn btn-outline-light" href="<?php echo $url->getUrl('grid','product'); ?>">Product</a>
				<a class="btn btn-outline-light" href="<?php echo $url->getUrl('grid','category'); ?>">Category</a>
				<a class="btn btn-outline-light" href="<?php echo $url->getUrl('grid','customer'); ?>">Customer</a>
				<a class="btn btn-outline-light" href="<?php echo $url->getUrl('grid','vendor'); ?>">Vendor</a>
				<a class="btn btn-outline-light" href="<?php echo $url->getUrl('grid','salesman'); ?>">Salesman</a>
	</nav>
</div>
<?php

require_once 'Model/Core/Message.php';

$msgheader = new Model_Core_Message();
$msgs = $msgheader->getMessage();
// print_r($msgs);
if($msgs){
	foreach($msgs as $type=>$message){
		echo "<p class='{$type}'>";
		echo $message;
		echo "</p>";
	}
}

$msgheader->clearMessage();
?>

	
