<?php 
$result = $this->salesman->getData();
?>

<div>
	<table class="tc">
		<tr>
			<td> <h3> MANAGE SALESMAN</h3></td>
			<td>  <a href="<?php echo $url->getUrl('add','salesman'); ?>" class="btn btn-primary ms-5">Add Salesman</a> </td>
		</tr>
	</table>
</div>
<table border="1" cellspacing="0" class="tc table table-striped table-bordered">
	<tr style="height: 30px; font-size: 18px;">
		<th>sales_id</th>
		<th>first name</th>
		<th>last name</th>
		<th>email</th>
		<th>gender</th>
		<th>status</th>
		<th>created_at</th>
		<th>updated_at</th>
		<th>EDIT</th>
		<th>DELETE</th>
	</tr>

	<?php 
	foreach ($result as $sale):
		?>
		<tr class="center">
			<td><?php echo $sale->sales_id; ?></td>
			<td><?php echo $sale->fname; ?></td>
			<td><?php echo $sale->lname; ?></td>
			<td><?php echo $sale->email; ?></td>
			<td><?php echo $sale->gender; ?></td>
			<td><?php echo $sale->status; ?></td>
			<td><?php echo $sale->created_at; ?></td>
			<td><?php echo $sale->updated_at; ?></td>
			<td><a href="<?php echo $url->getUrl('edit','salesman',['id'=>$sale->sales_id]); ?>">Edit</td>
			<td><a href="<?php echo $url->getUrl('delete','salesman',['id'=>$sale->sales_id]); ?>">Delete</td>
		</tr>
			<?php 
			endforeach;
			?>
		</table>
</div>

<?php $pager = $this->getPager();?>
	<table width="60%">
		<tr>
			<td><a href="index.php?a=grid&c=salesman&p=<?php echo $pager->start; ?>" class="btn btn-primary  " id="start">START</a> </td>
			<td><a href="index.php?a=grid&c=salesman&p=<?php echo $pager->previous; ?>" class="btn btn-primary  " id="previous">PREV</a> </td>
			<td><a href="index.php?a=grid&c=salesman&p=<?php echo $pager->currentPage; ?>" class="btn btn-primary  ">CURRENT</a></td>
			<td><a href="index.php?a=grid&c=salesman&p=<?php echo $pager->next; ?>" class="btn btn-primary  " id="next">NEXT</a> </td>
			<td><a href="index.php?a=grid&c=salesman&p=<?php echo $pager->end; ?>" class="btn btn-primary  " id="end">END</a> </td>
			<p> Showing <strong><?php echo $pager->getCurrentPage(); ?></strong> of <strong><?php echo $pager->numberOfPages; ?></strong> Pages </p>
		</tr>
	</table>
</table>
<script type="text/javascript">
		$(document).ready(function(){
			if(<?php echo $pager->getCurrentPage() ?> === 1){
			$('#start').addClass('disabled');
			$('#previous').addClass('disabled');
			}

			if(<?php echo $pager->getCurrentPage(); ?> === <?php echo $pager->numberOfPages; ?>){
			$('#end').addClass('disabled');
			$('#next').addClass('disabled');
			}
		});
	</script>
